---
# tasks file for control-plane-lb
#
#
- name: install haproxy
  apt: name={{item}} state=present
  with_items: 
        - haproxy

- name: add haproxy conf
  copy:
          src: haproxy.cfg
          dest: /etc/haproxy/haproxy.cfg

- name: enable and restart haproxy
  become: true
  shell: systemctl enable haproxy && systemctl restart haproxy

- name: install cfssl
  become: true
  shell: wget https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 && \
        wget https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64 && \
        chmod +x cfssl* && \
        mv cfssl_linux-amd64 /usr/local/bin/cfssl && \
        mv cfssljson_linux-amd64 /usr/local/bin/cfssljson

- name: copy cfssl files
  copy:
          src: "{{item}}"
          dest: /home/{{ansible_user}}
  with_items: 
        - ca-config.json
        - ca-csr.json
        - kubernetes-csr.json

- name: generate cfssl certs
  shell: cd /home/{{ansible_user}} && cfssl gencert -initca ca-csr.json | cfssljson -bare ca && \
        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -hostname=192.168.0.30,192.168.0.31,192.168.0.32,192.168.0.33,127.0.0.1,kubernetes.default \
        -profile=kubernetes kubernetes-csr.json | \
        cfssljson -bare kubernetes

- name: fetch cfssl certs
  fetch:
          src: /home/{{ansible_user}}/{{item}}
          dest: ~/ansible/cfssl
  with_items:
          - ca.pem
          - kubernetes.pem
          - kubernetes-key.pem
