apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- 192.168.0.30
controlPlaneEndpoint: "192.168.0.30:6443"
etcd:
  external:
    endpoints:
    - https://192.168.0.31:2379
    - https://192.168.0.32:2379
    - https://192.168.0.33:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24
apiServerExtraArgs:
  apiserver-count: "3"
