---
# tasks file for kubernetes
- name: add apt key
  become: true
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  
- name: add apt repo
  become: true
  shell: add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  
- name: install kubernetes
  become: true
  apt: name={{item}} state=present
  with_items:
          - kubeadm
          - kubectl
          - kubelet
  tags: [ 'packages' ]

- name: disable swap
  become: true
  shell: swapoff -a

- name: disable swap on fstab
  become: true
  shell: sed -i '/ swap / s/^/#/' /etc/fstab

  #- name: add kubernetes workers to hosts
  #become: true
  #shell: echo {{item}} >> /etc/hosts
  #with_inventory_hostnames:
  #        - kubernetes
  #        - kubernetes-master
  #        - gluster
